version: '3'

services:
  rails:
    build:
      dockerfile: docker/development/Dockerfile
      context: .
    image: do-zero-rails
    env_file: .env
    stdin_open: true
    tty: true
    volumes:
      - .:/project
      - bundle_data:/bundle
      - $HOME/.ssh:/project/docker/development/home/.ssh
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # sidekiq:
  #   build:
  #     dockerfile: docker/development/Dockerfile
  #     context: .
  #   image: rails
  #   entrypoint: "docker/development/sidekiq-entrypoint"
  #   env_file: .env
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - .:/project
  #     - bundle_data:/bundle
  #     - $HOME/.ssh:/project/docker/development/home/.ssh
  #   depends_on:
  #     - redis
  #   networks:
  #     - default

  # redis:
  #   image: redis:6
  #   restart: on-failure
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis_data:/data

volumes:
  bundle_data:
  postgres_data:
  # redis_data:
