#!/bin/sh
set -e

echo "=== RUBOCOP ==="
rubocop --parallel

echo "=== BRAKEMAN ==="
brakeman -o /dev/stdout --color

echo "=== BUNDLER AUDIT ==="
bundle-audit update
bundle-audit

echo "=== YARN AUDIT ==="
yarn audit
